name: Update README

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente
  push:
    branches:
      - main  # Atualiza quando houver um push na branch main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Commits Count
        run: |
          commits=$(git rev-list --count HEAD)
          sed -i "s/<!-- commits -->/[${commits}](#commits)/" README.md

      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update commits count"
          git push
